language: rust
sudo: false
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly
    - rust: beta
      env: FEATURES=''
    - rust: stable
      env: FEATURES=''
script:
   - cargo build --features "$FEATURES"
